In [1]:
import pandas as pd

In [2]:
table_file= "cities.csv"

In [3]:
table_df = pd.read_csv(table_file, encoding="utf-8")

In [4]:
table_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,jacareacanga,0,BR,1528902000,62,-6.22,-57.76,89.60,6.93
1,1,kaitangata,100,NZ,1528905304,94,-46.28,169.85,42.61,5.64
2,2,goulburn,20,AU,1528905078,91,-34.75,149.72,44.32,10.11
3,3,lata,76,IN,1528905305,89,30.78,78.62,59.89,0.94
4,4,chokurdakh,0,RU,1528905306,88,70.62,147.90,32.17,2.95

In [5]:
table_df = table_df.set_index("City_ID")
table_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
City_ID,,,,,,,,,
0,jacareacanga,0,BR,1528902000,62,-6.22,-57.76,89.60,6.93
1,kaitangata,100,NZ,1528905304,94,-46.28,169.85,42.61,5.64
2,goulburn,20,AU,1528905078,91,-34.75,149.72,44.32,10.11
3,lata,76,IN,1528905305,89,30.78,78.62,59.89,0.94
4,chokurdakh,0,RU,1528905306,88,70.62,147.90,32.17,2.95
5,martyush,92,RU,1528905306,94,56.40,61.89,55.03,9.33
6,hobart,20,AU,1528902000,87,-42.88,147.33,44.60,8.05
7,broken hill,0,AU,1528905311,88,-31.97,141.45,44.50,7.31
8,harnosand,0,SE,1528903200,44,62.63,17.94,60.80,13.87
9,tuatapere,0,NZ,1528905312,100,-46.13,167.69,38.92,3.40
10,puerto ayora,90,EC,1528902000,69,-0.74,-90.35,77.00,13.87
11,havre-saint-pierre,75,CA,1528902000,58,50.23,-63.60,53.60,19.46
12,punta arenas,0,CL,1528902000,100,-53.16,-70.91,35.60,9.17
13,tasiilaq,75,GL,1528901400,60,65.61,-37.64,39.20,2.24
14,chapais,40,CA,1528902000,38,49.78,-74.86,59.00,10.29
15,avarua,40,CK,1528902000,56,-21.21,-159.78,73.40,10.29
16,hofn,75,IS,1528902000,87,64.25,-15.21,51.80,8.05
17,yukamenskoye,92,RU,1528905315,98,57.89,52.24,56.65,10.22
18,khandbari,80,NP,1528905315,67,27.38,87.21,44.59,1.39
19,bethel,1,US,1528901580,93,60.79,-161.76,44.60,8.05
20,ushuaia,75,AR,1528902000,64,-54.81,-68.31,41.00,3.36
21,east london,0,ZA,1528902000,37,-33.02,27.91,69.80,5.82
22,bluff,76,AU,1528905321,76,-23.58,149.07,61.96,4.74
23,mount isa,75,AU,1528902000,100,-20.73,139.49,64.40,3.29
24,pevek,0,RU,1528905321,71,69.70,170.27,36.94,6.98
25,gao,24,ML,1528905321,16,16.28,-0.04,110.02,4.97
26,cabo san lucas,75,MX,1528901160,74,22.89,-109.91,84.20,10.29
27,sao filipe,0,CV,1528905323,88,14.90,-24.50,75.73,13.02
28,tiksi,44,RU,1528905298,58,71.64,128.87,57.73,10.11
29,busselton,92,AU,1528905323,100,-33.64,115.35,60.43,10.56
...,...,...,...,...,...,...,...,...,...
517,kochi,90,IN,1528903800,94,9.96,76.25,77.00,2.24
518,notse,56,TG,1528905594,76,6.95,1.17,86.62,8.77
519,amuntai,36,ID,1528905596,88,-2.42,115.25,77.17,2.17
520,san juan,90,PH,1528902000,100,14.60,121.03,77.00,10.29
521,rocha,56,UY,1528905597,93,-34.48,-54.34,49.99,21.18
522,elizabeth city,90,US,1528904640,83,36.30,-76.22,78.80,12.75
523,narathiwat,75,TH,1528902000,83,6.43,101.80,82.40,4.70
524,acari,0,BR,1528905599,48,-6.44,-36.64,84.10,15.26
525,puerto carreno,40,CO,1528902000,74,6.19,-67.49,84.20,3.36
526,troitskiy,0,RU,1528903800,48,45.15,38.14,82.40,6.71
527,dhidhdhoo,88,MV,1528905605,100,6.88,73.10,82.39,12.24
528,santa fe,12,AR,1528905642,84,-31.62,-60.70,47.47,10.45
529,kuytun,20,RU,1528905610,73,54.34,101.51,64.30,2.62
530,evans,1,US,1528904100,41,40.38,-104.69,78.80,3.36
531,sokoni,0,CD,1528905646,37,-12.89,28.78,74.56,4.07
532,sovetskiy,76,RU,1528905619,85,56.76,48.47,61.33,14.03
533,pagudpud,90,PH,1528902000,100,18.56,120.79,77.00,13.87
534,southbridge,90,US,1528903440,82,42.08,-72.03,69.80,19.46
535,brazzaville,8,CD,1528902000,55,-4.27,15.27,86.00,5.82
536,tutoia,40,BR,1528902000,52,-2.76,-42.27,91.40,8.05
537,harlingen,75,US,1528902900,62,26.19,-97.70,89.60,10.29
538,calamar,92,CO,1528905629,100,1.96,-72.65,70.87,2.95
539,road town,40,VG,1528905600,66,18.42,-64.62,87.80,12.75
540,tabas,36,IR,1528905630,11,33.60,56.92,94.27,6.98
541,shieli,88,KZ,1528905630,41,44.18,66.74,67.27,14.81
542,scalea,36,IT,1528905631,100,39.82,15.79,70.06,5.30
543,san andres,68,PH,1528905632,100,13.32,122.68,83.47,22.64
544,muisne,92,EC,1528905633,84,0.61,-80.02,76.90,4.63
545,ati,20,TD,1528905633,25,13.21,18.34,104.53,4.97
546,san luis,0,AR,1528905472,53,-33.30,-66.34,42.43,2.62

In [6]:
table_df.to_html("table.html")

In [7]:
table_df.to_html("table_test.html")